version: "3.7"

services:
  api:
    build: ./api
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - 3000:3000
  app:
    build: ./app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 1234:1234
    depends_on:
      - api
