module.exports = localization = {
  en: {
    home: "Home",
    back: "Go back",
    choose_language: "Choose language",
    my_lists: "My lists",
    new_list: "New list",
    add_new_list: "Create new list",
    add_new_list_placeholder: "What's the name of your list?",
    products: "Products",
    options: "Options",
    yes: "Yes",
    no: "No",
    are_you_sure: "Are you sure?",
    delete_list: "Do you want to delete this list?",
    add_more: "Add more",
    done: "Done",
    add_category: "Add a category",
    cancel: "Cancel",
    modal_input: "Write here...",
    choose_name_input: "Choose a name",
    add_product: "Add a product",
    delete_category: "Do you want to delete this category?",

  },
  es: {
    home: "Inicio",
    back: "Retroceder",
    choose_language: "Elige idioma",
    my_lists: "Mis listas",
    new_list: "Nueva lista",
    add_new_list: "Crear nueva lista",
    add_new_list_placeholder: "¿Cómo se llama tu lista?",
    products: "Productos",
    options: "Opciones",
    yes: "Sí",
    no: "No",
    are_you_sure: "¿Estás seguro/a?",
    delete_list: "¿Quieres borrar esta lista?",
    add_more: "Añadir más",
    done: "Hecho",
    add_category: "Añade otra categoría",
    cancel: "Cancelar",
    modal_input: "Escribe aquí...",
    choose_name_input: "Elige un nombre",
    add_product: "Añade un producto",
    delete_category: "¿Quieres borrar esta categoría?",

    
  }
}